### ISSUE TITLE
User Story: Checkout process

### ISSUE THREAD

**Issue by starmarke** [yellowsub12/SOEN-341#4]
About this issue
Story Points: 8
Priority: Medium
Risk: High

Story Description:
After logging into the website, customers can choose or set some personal options, such as how to pay (PayPal, credit card or debit card).

**Comment by starmarke** [comment]
After logging into the website, customers can choose or set some personal options, such as how to pay (PayPal, credit card or debit card), or whether they are willing to accept preferential products by mail

**Comment by yellowsub12** [comment]
Backend completed in commit 7a1d2d5 from Reactbranchpay by myself.
