### ISSUE TITLE
Develop frontend homepage 

### ISSUE THREAD

**Issue by yellowsub12** [yellowsub12/SOEN-341#8]
About this issue
Story Points: 2
Priority: High
Risk: Low

Story Description:
Create a proper frontend homepage. Tasks to be completed for this

-Header (Oussama) #9
-Footer (Kevin) #10 
-Slide (Ali) #11 
-Item display (Vithu) #13
-Foot-login (Mariam) #12

**Comment by samdarshihawk** [comment]
As a normal user, I would like to receive basic information about a site through the header. Sub-story of User Story #8 #9
